# -*- coding: utf-8 -*-
"""CyberThreatVisual.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WoaQAbDZ1jonA1CJzJIAmRHasetUuH-7
"""

import pandas as pd

df = pd.read_csv('/Global_Cybersecurity_Threats_2015-2024.csv')
df.head()

df.info()
df.columns

# Show summary statistics
df['Financial Loss (in Million $)'].describe()

# Check for missing values
df['Financial Loss (in Million $)'].isnull().sum()

# Remove extra spaces, unify attack names
df['Attack Type'] = df['Attack Type'].str.strip().str.title()
df['Target Industry '] = df['Target Industry'].str.strip().str.title()

# Ensure Year is numeric
df['Year'] = pd.to_numeric(df['Year'], errors='coerce')
df = df.dropna(subset=['Year', 'Attack Type', 'Target Industry'])  # Remove incomplete rows

!pip install seaborn plotly

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

"""Line Chart – Number of Attacks per Year


"""

attacks_per_year = df['Year'].value_counts().sort_index()

plt.figure(figsize=(10, 5))
sns.lineplot(x=attacks_per_year.index, y=attacks_per_year.values)
plt.title('Number of Cyber Attacks Over the Years')
plt.xlabel('Year')
plt.ylabel('Number of Attacks')
plt.grid(True)
plt.tight_layout()
plt.show()

"""Bar Chart – Top 10 Attack Types"""

attack_counts = df['Attack Type'].value_counts().nlargest(10)

plt.figure(figsize=(10, 6))
sns.barplot(x=attack_counts.values, y=attack_counts.index)
plt.title('Top 10 Cyber Attack Types')
plt.xlabel('Number of Incidents')
plt.ylabel('Attack Type')
plt.tight_layout()
plt.show()

""" Pie Chart – Industry-wise Distribution"""

industry_counts = df['Target Industry'].value_counts().nlargest(10)
industry_counts.plot.pie(autopct='%1.1f%%', figsize=(8,8), title='Top 10 Industries Affected by Cyber Attacks')
plt.ylabel('')
plt.show()

"""Heatmap – Frequency of Attacks by Year and Industry"""

heatmap_data = df.groupby(['Year', 'Target Industry']).size().unstack().fillna(0)

plt.figure(figsize=(14, 8))
sns.heatmap(heatmap_data, cmap='Reds', linewidths=0.5)
plt.title('Cyber Attacks by Year and Industry')
plt.xlabel('Target Industry')
plt.ylabel('Year')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""Scatter Plot: Year vs Financial Loss

"""

plt.figure(figsize=(10,6))
sns.scatterplot(data=df, x='Year', y='Financial Loss (in Million $)', hue='Attack Type')
plt.title('Financial Loss Over the Years by Attack Type')
plt.tight_layout()
plt.show()

"""World Map – Attack Count by Country"""

country_counts = df['Country'].value_counts().reset_index()
country_counts.columns = ['Country', 'Attack Count']

fig = px.choropleth(country_counts,
                    locations="Country",
                    locationmode='country names',
                    color="Attack Count",
                    color_continuous_scale="Reds",
                    title="Global Cyber Attacks by Country")
fig.show()

"""Timeline Chart – Top Cyber Incidents Over Years"""

timeline_df = df[['Year', 'Attack Type', 'Target Industry']].drop_duplicates().sort_values(by='Year').head(10)
timeline_df

"""Box Plot: Financial Loss by Attack Type"""

top_attacks = df['Attack Type'].value_counts().nlargest(5).index
filtered_df = df[df['Attack Type'].isin(top_attacks)]

plt.figure(figsize=(12,6))
sns.boxplot(data=filtered_df, x='Attack Type' , y='Financial Loss (in Million $)')
plt.title('Financial Loss Distribution by Top Attack Types')
plt.tight_layout()
plt.show()

"""Stacked Bar Chart – Attack Type Trends Over Years"""

attack_trend = df.groupby(['Year', 'Attack Type']).size().unstack().fillna(0)

attack_trend.plot(kind='bar', stacked=True, figsize=(14,6), colormap='tab20')
plt.title('Stacked Cyber Attack Types by Year')
plt.xlabel('Year')
plt.ylabel('Number of Incidents')
plt.legend(loc='upper right', bbox_to_anchor=(1.15, 1))
plt.tight_layout()
plt.show()